const ISO_CODES: Record<string, string> = {
  andorra: "AD",
  "united arab emirates": "AE",
  "arab emirates": "AE",
  "antigua and barbuda": "AG",
  anguilla: "AI",
  armenia: "AM",
  angola: "AO",
  "american samoa": "AS",
  austria: "AT",
  aruba: "AW",
  "bosnia and herzegovina": "BA",
  barbados: "BB",
  bangladesh: "BD",
  "burkina faso": "BF",
  bulgaria: "BG",
  bahrain: "BH",
  burundi: "BI",
  benin: "BJ",
  bermuda: "BM",
  bahamas: "BS",
  bhutan: "BT",
  botswana: "BW",
  belarus: "BY",
  belize: "BZ",
  "central african republic": "CF",
  congo: "CG",
  switzerland: "CH",
  "côte d'ivoire": "CI",
  chile: "CL",
  cameroon: "CM",
  china: "CN",
  "costa rica": "CR",
  germany: "DE",
  denmark: "DK",
  dominica: "DM",
  algeria: "DZ",
  estonia: "EE",
  spain: "ES",
  fiji: "FJ",
  "united kingdom": "GB",
  uk: "GB",
  grenada: "GD",
  greenland: "GL",
  gambia: "GM",
  guinea: "GN",
  guadeloupe: "GP",
  guatemala: "GT",
  "guinea-bissau": "GW",
  "hong kong": "HK",
  honduras: "HN",
  croatia: "HR",
  haiti: "HT",
  indonesia: "ID",
  ireland: "IE",
  israel: "IL",
  iraq: "IQ",
  iceland: "IS",
  jamaica: "JM",
  japan: "JP",
  kyrgyzstan: "KG",
  cambodia: "KH",
  kuwait: "KW",
  kazakhstan: "KZ",
  lebanon: "LB",
  "sri lanka": "LK",
  lithuania: "LT",
  latvia: "LV",
  libya: "LY",
  "south korea": "KR",
  "republic of korea": "KR",
  "north korea": "KP",
  "united states of america": "US",
  usa: "US",
};

export function getFlagEmoji(countryName: string) {
  countryName = countryName.toLowerCase();
  const countryCode = ISO_CODES[countryName] ?? countryName.substring(0, 2);
  const offset = 0x1f1e6 - "A".charCodeAt(0);

  return countryCode
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(char.charCodeAt(0) + offset))
    .join("");
}
